import type { Worker, Payment, Company, DashboardStats, User } from "./types";

export const mockUsers: (User & { password: string })[] = [
  {
    id: "1",
    email: "admin@workforce.com",
    password: "admin123",
    name: "Alexander Mitchell",
    role: "admin",
  },
  {
    id: "2",
    email: "employee@workforce.com",
    password: "employee123",
    name: "Sarah Johnson",
    role: "employee",
  },
];

export const mockWorkers: Worker[] = [
  {
    id: "w1",
    name: "James Anderson",
    email: "james@workforce.com",
    phone: "+1 555-0101",
    position: "Senior Developer",
    assignedCompany: "TechCorp Inc.",
    status: "active",
    joinDate: "2024-01-15",
    salary: 8500,
    skills: ["React", "Node.js", "TypeScript"],
  },
  {
    id: "w2",
    name: "Maria Garcia",
    email: "maria@workforce.com",
    phone: "+1 555-0102",
    position: "UX Designer",
    assignedCompany: "DesignHub Ltd.",
    status: "active",
    joinDate: "2024-02-20",
    salary: 7200,
    skills: ["Figma", "UI/UX", "Prototyping"],
  },
  {
    id: "w3",
    name: "Robert Chen",
    email: "robert@workforce.com",
    phone: "+1 555-0103",
    position: "Data Analyst",
    assignedCompany: "DataFlow Systems",
    status: "on-leave",
    joinDate: "2023-11-10",
    salary: 6800,
    skills: ["Python", "SQL", "Tableau"],
  },
  {
    id: "w4",
    name: "Emily Watson",
    email: "emily@workforce.com",
    phone: "+1 555-0104",
    position: "Project Manager",
    assignedCompany: "TechCorp Inc.",
    status: "active",
    joinDate: "2024-03-05",
    salary: 9200,
    skills: ["Agile", "Scrum", "Leadership"],
  },
  {
    id: "w5",
    name: "David Kim",
    email: "david@workforce.com",
    phone: "+1 555-0105",
    position: "DevOps Engineer",
    assignedCompany: "CloudBase Corp.",
    status: "active",
    joinDate: "2024-01-28",
    salary: 8800,
    skills: ["AWS", "Docker", "Kubernetes"],
  },
  {
    id: "w6",
    name: "Lisa Thompson",
    email: "lisa@workforce.com",
    phone: "+1 555-0106",
    position: "QA Engineer",
    assignedCompany: "DesignHub Ltd.",
    status: "inactive",
    joinDate: "2023-09-15",
    salary: 6500,
    skills: ["Selenium", "Jest", "Cypress"],
  },
  {
    id: "w7",
    name: "Michael Brown",
    email: "michael@workforce.com",
    phone: "+1 555-0107",
    position: "Full Stack Developer",
    assignedCompany: "DataFlow Systems",
    status: "active",
    joinDate: "2024-04-12",
    salary: 8100,
    skills: ["React", "Python", "PostgreSQL"],
  },
  {
    id: "w8",
    name: "Jennifer Lee",
    email: "jennifer@workforce.com",
    phone: "+1 555-0108",
    position: "Business Analyst",
    assignedCompany: "CloudBase Corp.",
    status: "active",
    joinDate: "2024-02-01",
    salary: 7500,
    skills: ["Excel", "Power BI", "Requirements"],
  },
];

export const mockPayments: Payment[] = [
  {
    id: "p1",
    workerId: "w1",
    workerName: "James Anderson",
    assignedCompany: "TechCorp Inc.",
    amount: 8500,
    status: "paid",
    date: "2025-01-31",
    type: "salary",
  },
  {
    id: "p2",
    workerId: "w2",
    workerName: "Maria Garcia",
    assignedCompany: "DesignHub Ltd.",
    amount: 7200,
    status: "paid",
    date: "2025-01-31",
    type: "salary",
  },
  {
    id: "p3",
    workerId: "w3",
    workerName: "Robert Chen",
    assignedCompany: "DataFlow Systems",
    amount: 6800,
    status: "pending",
    date: "2025-02-28",
    type: "salary",
  },
  {
    id: "p4",
    workerId: "w4",
    workerName: "Emily Watson",
    assignedCompany: "TechCorp Inc.",
    amount: 9200,
    status: "pending",
    date: "2025-02-28",
    type: "salary",
  },
  {
    id: "p5",
    workerId: "w5",
    workerName: "David Kim",
    assignedCompany: "CloudBase Corp.",
    amount: 2000,
    status: "paid",
    date: "2025-01-15",
    type: "bonus",
  },
  {
    id: "p6",
    workerId: "w1",
    workerName: "James Anderson",
    assignedCompany: "TechCorp Inc.",
    amount: 8500,
    status: "overdue",
    date: "2024-12-31",
    type: "salary",
  },
  {
    id: "p7",
    workerId: "w6",
    workerName: "Lisa Thompson",
    assignedCompany: "DesignHub Ltd.",
    amount: 6500,
    status: "overdue",
    date: "2024-12-31",
    type: "salary",
  },
  {
    id: "p8",
    workerId: "w7",
    workerName: "Michael Brown",
    assignedCompany: "DataFlow Systems",
    amount: 8100,
    status: "paid",
    date: "2025-01-31",
    type: "salary",
  },
];

export const mockCompanies: Company[] = [
  {
    id: "c1",
    name: "TechCorp Inc.",
    industry: "Technology",
    workersAssigned: 2,
    contactPerson: "John Sterling",
    email: "contact@techcorp.com",
    status: "active",
  },
  {
    id: "c2",
    name: "DesignHub Ltd.",
    industry: "Design",
    workersAssigned: 2,
    contactPerson: "Anna Price",
    email: "contact@designhub.com",
    status: "active",
  },
  {
    id: "c3",
    name: "DataFlow Systems",
    industry: "Data Analytics",
    workersAssigned: 2,
    contactPerson: "Mark Rivers",
    email: "contact@dataflow.com",
    status: "active",
  },
  {
    id: "c4",
    name: "CloudBase Corp.",
    industry: "Cloud Services",
    workersAssigned: 2,
    contactPerson: "Diana Hart",
    email: "contact@cloudbase.com",
    status: "active",
  },
];

export const mockDashboardStats: DashboardStats = {
  totalWorkers: 8,
  activeCompanies: 4,
  pendingPayments: 2,
  totalRevenue: 285600,
};
